### ISSUE TITLE
PID is too "P" (proportional) and adjusts frequency too much

### ISSUE THREAD

**Issue by kuzetsa** [mlichvar/chrony#2]
According to $ chronyc tracking, the value for Frequency changes too much (*frequency changes which are greater than 0.05 ppm from one update to the next*) despite the following settings:

---

chrony.conf settings:

```
maxslewrate 0.014770
maxclockerror 0.0008450
```

**Comment by kuzetsa** [comment]
Additional info:

```
chronyd (chrony) version 3.0-pre2
built using gcc version 4.9.4 against glibc-2.23
Gentoo-based GNU userland with Linux kernel version 4.4.39

```

Various logging can be enabled and made available (*raw logs or otherwise*) if needed, and/or the rrdtool graph (*via munin plugin*) which I was using when I noticed this particular issue.

**Comment by mlichvar** [comment]
As we had discussed on #ntp, the maxslewrate and maxclockerror directives don't affect the tracking frequency, only frequency changes that make phase corrections. A new option will be needed to decrease changes in the tracking frequency.

This is just a mirror of the tuxfamily git repo and it would be better to take this to the chrony-dev mailing list, where more people are following the development.
