### ISSUE TITLE
Chrony-wait.service specifies both Before=time-sync.target and Wants=time-sync.target

### ISSUE THREAD

**Issue by LoyVanBeek** [mlichvar/chrony#3]
In https://github.com/mlichvar/chrony/blob/master/examples/chrony-wait.service

This seems conflicting to me, because chrony-wait .service wait for the time to be synced. The time is synced when the command is finished. 

Am I missing something?

**Comment by mlichvar** [comment]
I'm not sure where is the conflict. As I understand it, the time-sync target doesn't do anything. It's just used for ordering services. Services that need to be started with correct time have After=time-sync.target. The chrony-wait service, which is fully started up when chronyd has synchronized the clock, is ordered before the time-sync target, so when the target starts, the clock is already synchronized. Wants=time-sync.target enables starting of the target.

Is this causing any issues for you?

**Comment by LoyVanBeek** [comment]
Nope, no issues, just curiousity and wanting to learn systemd better. I was conflating ```Wants=``` and ```Before/After=```.
Enabling chrony-wait  now indeed simply also enables time-sync.target; ordering is done via the ```Before=```
